/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void nextButton_press(GButton source, GEvent event) { //_CODE_:nextButton:214512:
  println("nextButton - GButton >> GEvent." + event + " @ " + millis());
  next();
} //_CODE_:nextButton:214512:

public void previousButton_press(GButton source, GEvent event) { //_CODE_:previousButton:745614:
  println("previousButton - GButton >> GEvent." + event + " @ " + millis());
  previous();
} //_CODE_:previousButton:745614:

public void option1_clicked1(GOption source, GEvent event) { //_CODE_:option1:573085:
  println("option1 - GOption >> GEvent." + event + " @ " + millis());
  optionSelected(Option.A);
} //_CODE_:option1:573085:

public void option2_clicked1(GOption source, GEvent event) { //_CODE_:option2:517085:
  println("option2 - GOption >> GEvent." + event + " @ " + millis());
  optionSelected(Option.B);
} //_CODE_:option2:517085:

public void option3_clicked1(GOption source, GEvent event) { //_CODE_:option3:324490:
  println("option3 - GOption >> GEvent." + event + " @ " + millis());
  optionSelected(Option.C);
} //_CODE_:option3:324490:

public void option4_clicked1(GOption source, GEvent event) { //_CODE_:option4:724006:
  println("option4 - GOption >> GEvent." + event + " @ " + millis());
  optionSelected(Option.D);
} //_CODE_:option4:724006:

public void option5_clicked1(GOption source, GEvent event) { //_CODE_:option5:617348:
  println("option5 - GOption >> GEvent." + event + " @ " + millis());
  println("this should not happen");
} //_CODE_:option5:617348:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.CYAN_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  nextButton = new GButton(this, 570, 10, 60, 20);
  nextButton.setText("Next");
  nextButton.addEventHandler(this, "nextButton_press");
  previousButton = new GButton(this, 500, 10, 60, 20);
  previousButton.setText("Previous");
  previousButton.addEventHandler(this, "previousButton_press");
  togGroup1 = new GToggleGroup();
  option1 = new GOption(this, 260, 200, 120, 20);
  option1.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  option1.setText("option text");
  option1.setOpaque(false);
  option1.addEventHandler(this, "option1_clicked1");
  option2 = new GOption(this, 260, 220, 120, 20);
  option2.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  option2.setText("option text");
  option2.setOpaque(false);
  option2.addEventHandler(this, "option2_clicked1");
  option3 = new GOption(this, 260, 240, 120, 20);
  option3.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  option3.setText("option text");
  option3.setOpaque(false);
  option3.addEventHandler(this, "option3_clicked1");
  option4 = new GOption(this, 260, 260, 120, 20);
  option4.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  option4.setText("option text");
  option4.setOpaque(false);
  option4.addEventHandler(this, "option4_clicked1");
  option5 = new GOption(this, 640, 480, 120, 20);
  option5.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  option5.setText("option text");
  option5.setOpaque(false);
  option5.addEventHandler(this, "option5_clicked1");
  togGroup1.addControl(option1);
  togGroup1.addControl(option2);
  togGroup1.addControl(option3);
  togGroup1.addControl(option4);
  togGroup1.addControl(option5);
  option5.setSelected(true);
  questionLabel = new GLabel(this, 200, 170, 240, 20);
  questionLabel.setText("question text");
  questionLabel.setOpaque(false);
  titleLabel = new GLabel(this, 10, 10, 170, 20);
  titleLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  titleLabel.setText("AP Japanese Mock Exam");
  titleLabel.setOpaque(true);
  progressBar = new GView(this, 20, 440, 600, 20, JAVA2D);
  largeImage = new GView(this, 20, 70, 600, 360, JAVA2D);
  instructionsLabel = new GLabel(this, 100, 70, 440, 390);
  instructionsLabel.setTextAlign(GAlign.LEFT, GAlign.TOP);
  instructionsLabel.setText("Instructions");
  instructionsLabel.setOpaque(false);
  shortInstructionsLabel = new GLabel(this, 20, 40, 600, 20);
  shortInstructionsLabel.setText("short instructions");
  shortInstructionsLabel.setOpaque(false);
  timeLabel = new GLabel(this, 450, 10, 40, 20);
  timeLabel.setText("00:00");
  timeLabel.setOpaque(false);
  statusLabel = new GLabel(this, 190, 10, 110, 20);
  statusLabel.setText("Screen 15 of 36");
  statusLabel.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GButton nextButton; 
GButton previousButton; 
GToggleGroup togGroup1; 
GOption option1; 
GOption option2; 
GOption option3; 
GOption option4; 
GOption option5; 
GLabel questionLabel; 
GLabel titleLabel; 
GView progressBar; 
GView largeImage; 
GLabel instructionsLabel; 
GLabel shortInstructionsLabel; 
GLabel timeLabel; 
GLabel statusLabel; 
